// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinances.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyFinances.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704142940_AdicionaIndiceUnicoFaturaAberta")]
    partial class AdicionaIndiceUnicoFaturaAberta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyFinances.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Arquivada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("MyFinances.Models.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("DiaFechamento")
                        .HasColumnType("integer");

                    b.Property<int?>("DiaVencimento")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PierreAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("SaldoManual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("MyFinances.Models.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DataFechamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TransferenciaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContaId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'ABERTA'");

                    b.HasIndex("TransferenciaId")
                        .IsUnique();

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("MyFinances.Models.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConciliadoCom")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaFixaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("FaturaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Manual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Oculto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PierreTxnId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TransferenciaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ConciliadoCom");

                    b.HasIndex("ContaId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("PierreTxnId")
                        .IsUnique()
                        .HasFilter("\"PierreTxnId\" IS NOT NULL");

                    b.HasIndex("TransferenciaId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("MyFinances.Models.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaOrigemId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinoId");

                    b.HasIndex("ContaOrigemId");

                    b.ToTable("Transferencias");
                });

            modelBuilder.Entity("MyFinances.Models.Categoria", b =>
                {
                    b.HasOne("MyFinances.Models.Categoria", "Parent")
                        .WithMany("Subcategorias")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MyFinances.Models.Fatura", b =>
                {
                    b.HasOne("MyFinances.Models.Conta", "Conta")
                        .WithMany("Faturas")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFinances.Models.Transferencia", "Transferencia")
                        .WithOne("Fatura")
                        .HasForeignKey("MyFinances.Models.Fatura", "TransferenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conta");

                    b.Navigation("Transferencia");
                });

            modelBuilder.Entity("MyFinances.Models.Lancamento", b =>
                {
                    b.HasOne("MyFinances.Models.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinances.Models.Lancamento", "LancamentoConciliado")
                        .WithMany("LancamentosConciliados")
                        .HasForeignKey("ConciliadoCom")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinances.Models.Conta", "Conta")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFinances.Models.Fatura", "Fatura")
                        .WithMany("Lancamentos")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinances.Models.Transferencia", "Transferencia")
                        .WithMany("Lancamentos")
                        .HasForeignKey("TransferenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Fatura");

                    b.Navigation("LancamentoConciliado");

                    b.Navigation("Transferencia");
                });

            modelBuilder.Entity("MyFinances.Models.Transferencia", b =>
                {
                    b.HasOne("MyFinances.Models.Conta", "ContaDestino")
                        .WithMany("TransferenciasDestino")
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFinances.Models.Conta", "ContaOrigem")
                        .WithMany("TransferenciasOrigem")
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");
                });

            modelBuilder.Entity("MyFinances.Models.Categoria", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("MyFinances.Models.Conta", b =>
                {
                    b.Navigation("Faturas");

                    b.Navigation("Lancamentos");

                    b.Navigation("TransferenciasDestino");

                    b.Navigation("TransferenciasOrigem");
                });

            modelBuilder.Entity("MyFinances.Models.Fatura", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("MyFinances.Models.Lancamento", b =>
                {
                    b.Navigation("LancamentosConciliados");
                });

            modelBuilder.Entity("MyFinances.Models.Transferencia", b =>
                {
                    b.Navigation("Fatura");

                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
