// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinances.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyFinances.Migrations
{
    [DbContext(typeof(MyFinancesDbContext))]
    partial class MyFinancesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyFinances.Domain.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataCompra")
                        .HasColumnType("date")
                        .HasColumnName("data_compra");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("instituicao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorAtual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_atual");

                    b.Property<decimal>("ValorInvestido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_investido");

                    b.HasKey("Id");

                    b.ToTable("ativo", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Arquivada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("arquivada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.CompraParcelada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DataCompra")
                        .HasColumnType("date")
                        .HasColumnName("data_compra");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_parcelas");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.ToTable("compra_parcelada", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<int?>("DiaFechamento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_fechamento");

                    b.Property<int?>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origem");

                    b.Property<string>("PierreAccountId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pierre_account_id");

                    b.Property<decimal?>("SaldoManual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_manual");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("conta", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.ContaReceber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateOnly?>("DataPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista");

                    b.Property<DateOnly>("DataRegistro")
                        .HasColumnType("date")
                        .HasColumnName("data_registro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Pessoa")
                        .HasColumnType("text")
                        .HasColumnName("pessoa");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("conta_receber", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.DeParaCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CategoriaPierre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("categoria_pierre");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CategoriaPierre")
                        .IsUnique();

                    b.ToTable("de_para_categoria", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateOnly>("DataFechamento")
                        .HasColumnType("date")
                        .HasColumnName("data_fechamento");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContaId", "Status")
                        .IsUnique()
                        .HasDatabaseName("IX_fatura_conta_aberta")
                        .HasFilter("status = 'ABERTA'");

                    b.ToTable("fatura", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<Guid?>("CompraParceladaId")
                        .HasColumnType("uuid")
                        .HasColumnName("compra_parcelada_id");

                    b.Property<Guid?>("ConciliadoCom")
                        .HasColumnType("uuid")
                        .HasColumnName("conciliado_com");

                    b.Property<Guid?>("ContaFixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_fixa_id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<Guid?>("ContaReceberId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_receber_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("FaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("fatura_id");

                    b.Property<bool>("Manual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("manual");

                    b.Property<bool>("Oculto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("oculto");

                    b.Property<int?>("ParcelaNumero")
                        .HasColumnType("integer")
                        .HasColumnName("parcela_numero");

                    b.Property<string>("PierreTxnId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pierre_txn_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("TransferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("transferencia_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CompraParceladaId");

                    b.HasIndex("ConciliadoCom");

                    b.HasIndex("ContaId");

                    b.HasIndex("ContaReceberId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("PierreTxnId")
                        .IsUnique()
                        .HasDatabaseName("IX_lancamento_pierre_txn_id")
                        .HasFilter("pierre_txn_id IS NOT NULL");

                    b.HasIndex("TransferenciaId");

                    b.ToTable("lancamento", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContaDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_destino_id");

                    b.Property<Guid>("ContaOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_origem_id");

                    b.Property<Guid?>("ContaReceberId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_receber_id");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("FaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("fatura_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinoId");

                    b.HasIndex("ContaOrigemId");

                    b.HasIndex("ContaReceberId");

                    b.HasIndex("FaturaId");

                    b.ToTable("transferencia", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("MyFinances.Domain.Categoria", b =>
                {
                    b.HasOne("MyFinances.Domain.Categoria", "Parent")
                        .WithMany("Subcategorias")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MyFinances.Domain.ContaReceber", b =>
                {
                    b.HasOne("MyFinances.Domain.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MyFinances.Domain.DeParaCategoria", b =>
                {
                    b.HasOne("MyFinances.Domain.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MyFinances.Domain.Fatura", b =>
                {
                    b.HasOne("MyFinances.Domain.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("MyFinances.Domain.Lancamento", b =>
                {
                    b.HasOne("MyFinances.Domain.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinances.Domain.CompraParcelada", "CompraParcelada")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CompraParceladaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinances.Domain.Lancamento", "LancamentoConciliado")
                        .WithMany("LancamentosConciliados")
                        .HasForeignKey("ConciliadoCom")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinances.Domain.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinances.Domain.ContaReceber", "ContaReceber")
                        .WithMany()
                        .HasForeignKey("ContaReceberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinances.Domain.Fatura", "Fatura")
                        .WithMany("Lancamentos")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinances.Domain.Transferencia", "Transferencia")
                        .WithMany("Lancamentos")
                        .HasForeignKey("TransferenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("CompraParcelada");

                    b.Navigation("Conta");

                    b.Navigation("ContaReceber");

                    b.Navigation("Fatura");

                    b.Navigation("LancamentoConciliado");

                    b.Navigation("Transferencia");
                });

            modelBuilder.Entity("MyFinances.Domain.Transferencia", b =>
                {
                    b.HasOne("MyFinances.Domain.Conta", "ContaDestino")
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyFinances.Domain.Conta", "ContaOrigem")
                        .WithMany()
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinances.Domain.ContaReceber", "ContaReceber")
                        .WithMany()
                        .HasForeignKey("ContaReceberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyFinances.Domain.Fatura", "Fatura")
                        .WithMany("Transferencias")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");

                    b.Navigation("ContaReceber");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("MyFinances.Domain.Categoria", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("MyFinances.Domain.CompraParcelada", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("MyFinances.Domain.Fatura", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Transferencias");
                });

            modelBuilder.Entity("MyFinances.Domain.Lancamento", b =>
                {
                    b.Navigation("LancamentosConciliados");
                });

            modelBuilder.Entity("MyFinances.Domain.Transferencia", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
